# Use Node.js 20 to avoid deprecation warnings
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

# Build arguments for Supabase + Mail + JWT
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG MAIL_USER
ARG GMAIL_APP_PASSWORD
ARG JWT_SECRET

# Make them available during build
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV MAIL_USER=$MAIL_USER
ENV GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
ENV JWT_SECRET=$JWT_SECRET

# Build Next.js
RUN npm run build

EXPOSE 3000

# Runtime envs
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV MAIL_USER=$MAIL_USER
ENV GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
ENV JWT_SECRET=$JWT_SECRET

CMD ["npm", "start"]
