name: Deploy to Production Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ~/esprit-app
          
          # Pull latest code
          git pull origin main
          
          # Stop current containers
          docker-compose -f docker-compose.prod.yml down
          
          # Rebuild and start containers
          docker-compose -f docker-compose.prod.yml up -d --build
          
          # Clean up old images
          docker image prune -f
          
          echo "Deployment completed successfully!"
